
default: &default
  adapter: postgresql
  encoding: unicode
  username: vagrant
  # host: localhost
  pool: 5

development:
  <<: *default
  database: playlist_development

test:
  <<: *default
  database: playlist_test

production:
  <<: *default
  database: playlist_production
  password: <%= ENV['playlist_DATABASE_PASSWORD'] %>
